AWSTemplateFormatVersion: 2010-09-09
Description: |
  The Roman Numerals Converter Application aims to convert the given number to the Roman numerals. The application is to be coded in Python and deployed as a web application with Flask on AWS Elastic Compute Cloud (EC2) Instance using AWS Cloudformation and CLI Services.

Parameters:  # Key Name seçmek için parametre giriyoruz
  KeyName: 
    Description: aysunKEY
    Type: AWS::EC2::KeyPair::KeyName

Resources:  # http ve ssh bağlantısı için security grup oluşturuyoruz
  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH for Flask Web Server
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  WebServerHost:  # ağa bağlanacak ec2 oluşturuyoruz
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05fa00d4c63e32376  # N.Virginia ami id giriyoruz
      InstanceType: t2.micro
      KeyName: !Ref KeyName 
      SecurityGroupIds:
        - !Ref WebServerSecGroup  # ec2 nun kullanacağı secgrubu yukarıdakini ref ediyoruz
      Tags:
        - Key: Name
          Value: !Sub WebServer of ${AWS::StackName} Stack  # İnstance isminin orada gözükecek StackName
      UserData: !Base64 |
        #!/bin/bash 
        yum update -y
        yum install python3 -y
        pip3 install flask
        cd /home/ec2-user
        wget https://raw.githubusercontent.com/f4354aysun/aws-proje-01/main/Project-001-Roman-Numerals-Converter/app.py
        mkdir templates
        cd templates
        wget https://raw.githubusercontent.com/f4354aysun/aws-proje-01/main/Project-001-Roman-Numerals-Converter/templates/index.html
        wget https://raw.githubusercontent.com/f4354aysun/aws-proje-01/main/Project-001-Roman-Numerals-Converter/templates/result.html
        cd ..
        python3 app.py      

Outputs:
  WebsiteURL:
    Value: !Sub  # !sub giriş dizesindeki değişkenleri belirtilen değerle değiştirir
      - http://${PublicAddress}  # return edilecek değeri girdik
      - PublicAddress: !GetAtt WebServerHost.PublicDnsName  # getatt template deki bi kaynaktan attribute döndürür
    Description: Roman Numerals Converter Application URL  # Description girdik